In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]

In [13]:
arr.ndim

5

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr1 = np.arange(1,11)
arr1 = arr1.reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr1[1][-1]

np.int64(10)

In [12]:
arr1[1][1:4]

array([7, 8, 9])

In [14]:
arr1.shape

(2, 5)

In [18]:
arr2 = np.array([6,10,8])
arr3 = np.array([3,5,2])
add = arr2 + arr3
print(add)
sub = arr2 - arr3
print(sub)
prod = arr2 * arr3
print(prod)
div = arr2 / arr3
print(div)

[ 9 15 10]
[3 5 6]
[18 50 16]
[2. 2. 4.]

In [22]:
np.mean(arr2)

np.float64(8.0)

In [23]:
np.max(arr2)

np.int64(10)

In [25]:
durations = np.array([3,12,5,7])
avg = np.mean(durations)
median = np.median(durations)
std_dev = np.std(durations)
print("Average:", avg)
print("Median:", median)
print("Standard Deviation:", std_dev)

Average: 6.75
Median: 6.0
Standard Deviation: 3.344772040064913

In [26]:
newarr = np.arange(1,16)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#reshape
newarr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
newarr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
import pandas as pd

In [34]:
df = pd.DataFrame({'Name': ['Saanvi', 'Rimjhim', 'Ritu'], 'Age': [19, 19, 20], 'City': ['Bareilly', 'Jaunpur', 'Gorakhpur']})
df

      Name  Age       City
0   Saanvi   19   Bareilly
1  Rimjhim   19    Jaunpur
2     Ritu   20  Gorakhpur

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [36]:
df.describe()

             Age
count   3.000000
mean   19.333333
std     0.577350
min    19.000000
25%    19.000000
50%    19.000000
75%    19.500000
max    20.000000

In [38]:
list(df.columns)

['Name', 'Age', 'City']

In [40]:
df['City']

0     Bareilly
1      Jaunpur
2    Gorakhpur
Name: City, dtype: str

In [42]:
df.iloc[2] = ['Taylor Swift', 30, 'NYC']
df

           Name  Age      City
0        Saanvi   19  Bareilly
1       Rimjhim   19   Jaunpur
2  Taylor Swift   30       NYC

In [43]:
#how to add a new column in the dataframe
df['cgpa'] = [9.5, 9.2, 9.8]
df

           Name  Age      City  cgpa
0        Saanvi   19  Bareilly   9.5
1       Rimjhim   19   Jaunpur   9.2
2  Taylor Swift   30       NYC   9.8

In [45]:
df.drop(2)

      Name  Age      City  cgpa
0   Saanvi   19  Bareilly   9.5
1  Rimjhim   19   Jaunpur   9.2

In [46]:
df = df.reset_index()

In [49]:
df.drop('City', axis=1)
df

   index          Name  Age      City  cgpa
0      0        Saanvi   19  Bareilly   9.5
1      1       Rimjhim   19   Jaunpur   9.2
2      2  Taylor Swift   30       NYC   9.8

In [50]:
newdf= pd.read_csv('students.csv')
newdf

    Student_ID Branch  Study_Hours  Attendance  Marks Grade
0            1     ME          5.3          70     75     A
1            2     CE          2.0          99     68     B
2            3    CSE          3.0          72     59     C
3            4     ME          3.6          78     70     B
4            5     ME          4.2          80     69     B
5            6     CE          6.5          79     74     B
6            7    CSE          2.4          99     64     B
7            8    CSE          4.6          95     81     A
8            9     ME          5.1          83     72     B
9           10    ECE          1.3          69     60     B
10          11     ME          5.3          99     61     B
11          12     ME          2.2          55     57     C
12          13     ME          1.5          79     54     C
13          14     ME          7.6          61     78     A
14          15     CE          7.8          63     82     A
15          16    CSE          6.7          78     67     B
16          17     CE          3.1          55     55     C
17          18     CE          1.7          98     60     B
18          19     CE          5.8          62     80     A
19          20     ME          4.1          78     63     B
20          21    ECE          1.9          65     48     C
21          22    CSE          4.5          71     64     B
22          23    ECE          1.2          62     54     C
23          24     CE          7.4          89     87     A
24          25     CE          2.8          89     59     C
25          26    ECE          5.6          87     78     A
26          27    ECE          3.2          59     58     C
27          28    ECE          4.6          96     78     A
28          29     CE          4.8          93     68     B
29          30     CE          2.3          95     59     C
30          31    CSE          7.8          82     83     A
31          32    CSE          6.4          61     65     B
32          33     CE          7.6          63     82     A
33          34    ECE          7.3          62     80     A
34          35    ECE          5.2          66     69     B
35          36    CSE          7.5          88     84     A
36          37     CE          1.6          87     47     C
37          38    CSE          2.4          77     55     C
38          39    CSE          1.3          78     50     C
39          40     ME          3.3          91     60     B

In [ ]:
newdf['Marks'].mean()  #avg marks

np.float64(66.925)

In [52]:
newdf['Attendance'].median()  #median attendance

np.float64(78.0)

In [53]:
newdf['Branch'].mode()  #most common branch

0    CE
Name: Branch, dtype: str